<div style="margin-top: 30px;" class="container jumbotron">
    <h1 style="text-align: center;">Welcome to Simply Classified!!!</h1>
    <h5 style="text-align: center;">Here you can find best products from around Canada...</h5>
    <a href="?page=items" class="btn btn-primary m-4 font-weight-bold" role="button"><i class="fas fa-sitemap"></i> List Items  &nbsp;&nbsp;<i class="fas fa-chevron-circle-right"></i></a>
</div>

<section class="container jumbotron">
    <?php echo $homeProductContent?>
</section>