<div style="margin-top: 30px;" class="container jumbotron">
    <a href="?page=items" class="btn btn-primary m-4 font-weight-bold" role="button"><i class="fas fa-sitemap"></i> List Items  &nbsp;&nbsp;<i class="fas fa-chevron-circle-right"></i></a>
    <a href="?page=category" class="btn btn-primary m-4 font-weight-bold" role="button"><i class="fas fa-sitemap"></i> List Categories &nbsp;&nbsp; <i class="fas fa-chevron-circle-right"></i></a>
</div>

<div style="margin-top: 30px;" class="container jumbotron">
    <p class="h5">Select which items appear in HomePage</p>
    <?=$homeItemselect?>
</div>